module.exports = {
  TEST: 'TEST',
  INIT_STATE_SUCCESS: 'INIT_STATE_SUCCESS',
  INIT_STATE_REQUEST: 'INIT_STATE_REQUEST',
  INIT_STATE: 'INIT_STATE',
  TOKEN: 'TOKEN',

  ADD_VOTE: 'ADD_VOTE',
  VOTE_ADDED: 'VOTE_ADDED',

  NEW_QUESTION: 'NEW_QUESTION',

  NEW_CANDIDATE : "NEW_CANDIDATE",
  REMOVE_CANDIDATE : "REMOVE_CANDIDATE"
}
